image: maven:latest

variables:
  GIT_STRATEGY: clone

before_script:
  - echo "Pipeline Started"
  - chmod 777 ./mvnw

stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - ugrad
  script:
    - echo "Build Stage Started"
    - ./mvnw clean install -DskipTests
  artifacts:
    paths:
      - "**/target/*.jar"


test:
  stage: test
  tags:
    - ugrad
  script:
    - echo "Test Stage Started"
    - ./mvnw test
  artifacts:
    paths:
      - "**/target/surefire-reports/TEST-*.xml"
    reports:
      junit:
        - "**/target/surefire-reports/TEST-*.xml"

#staging:
#  type: deploy
#  stage: staging
#  image: maven:latest
#  script:
#    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
#  only:
#    - staging

deploy:
  type: deploy
  tags:
    - ugrad
  stage: deploy
  image: maven:latest
  script:
    - echo "Deploy Stage Started"
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - heroku-deplyoment
#   TODO : change this to main

after_script:
  - echo "Pipeline Ended"
